import { ModuleData } from './types';

export const MODULES: ModuleData[] = [
  {
    id: 1,
    name: 'MATLAB Basics',
    shortName: 'Basics',
    challenges: [
      {
        id: 'M1_C1',
        module: 1,
        type: 'fix_bug',
        title: 'Variable Assignment',
        description: 'This code should assign the value 42 to a variable called "answer", then display it. Find and fix the bug.',
        brokenCode: 'anwser = 42;\ndisp(answer)',
        correctCode: 'answer = 42;\ndisp(answer)',
        expectedOutput: '    42',
        hints: [
          'Look carefully at the variable name on each line.',
          'The variable is spelled differently on line 1 vs line 2.',
          'Change "anwser" to "answer" on line 1.',
        ],
        explanation: 'MATLAB is case-sensitive and exact with variable names. "anwser" and "answer" are two different variables.',
        validator: (code) => {
          const lines = code.split('\n').map(l => l.trim()).filter(Boolean);
          return lines.some(l => /^answer\s*=\s*42\s*;?\s*$/.test(l)) &&
                 lines.some(l => /^disp\(\s*answer\s*\)\s*;?\s*$/.test(l));
        },
      },
      {
        id: 'M1_C2',
        module: 1,
        type: 'fix_bug',
        title: 'Suppressing Output',
        description: 'This code should assign x, y, z but only display z. Right now it displays all three. Fix it so only z shows.',
        brokenCode: 'x = 10\ny = 20\nz = 30',
        correctCode: 'x = 10;\ny = 20;\nz = 30',
        expectedOutput: 'z =\n    30',
        hints: [
          'In MATLAB, how do you prevent a line from printing its result?',
          'Use semicolons to suppress output on lines you don\'t want displayed.',
          'Add a semicolon at the end of the x and y lines.',
        ],
        explanation: 'A semicolon (;) at the end of a statement suppresses its output. Without it, MATLAB prints the result.',
        validator: (code) => {
          const lines = code.split('\n').map(l => l.trim()).filter(Boolean);
          const xLine = lines.find(l => /^x\s*=/.test(l));
          const yLine = lines.find(l => /^y\s*=/.test(l));
          const zLine = lines.find(l => /^z\s*=/.test(l));
          return !!xLine && xLine.endsWith(';') &&
                 !!yLine && yLine.endsWith(';') &&
                 !!zLine && !zLine.endsWith(';');
        },
      },
      {
        id: 'M1_C3',
        module: 1,
        type: 'fix_bug',
        title: 'Creating a Row Vector',
        description: 'This code should create a row vector [1, 2, 3, 4, 5] but creates a column vector instead. Fix it.',
        brokenCode: 'v = [1; 2; 3; 4; 5];\ndisp(v)',
        correctCode: 'v = [1, 2, 3, 4, 5];\ndisp(v)',
        expectedOutput: '     1     2     3     4     5',
        hints: [
          'What is the difference between commas and semicolons inside square brackets?',
          'Semicolons inside [] create new rows. Commas (or spaces) separate columns.',
          'Replace the semicolons inside the brackets with commas.',
        ],
        explanation: 'In MATLAB, semicolons separate rows and commas/spaces separate columns. [1;2;3] is a column vector, [1,2,3] is a row vector.',
        validator: (code) => {
          const match = code.match(/v\s*=\s*\[([^\]]+)\]/);
          if (!match) return false;
          const inner = match[1];
          return !inner.includes(';') && /1/.test(inner) && /5/.test(inner);
        },
      },
      {
        id: 'M1_C4',
        module: 1,
        type: 'predict_output',
        title: 'Predict: Workspace Variables',
        description: 'What does this code display?\n\na = 3;\nb = 7;\nc = a + b',
        brokenCode: 'a = 3;\nb = 7;\nc = a + b',
        correctCode: 'c =\n\n    10',
        expectedOutput: '10',
        hints: [
          'Semicolons suppress output. Which lines have semicolons?',
          'Only the last line (c = a + b) has no semicolon, so only c is displayed.',
          'c = 3 + 7 = 10, and it\'s the only unsuppressed output.',
        ],
        explanation: 'Lines ending with ; are silent. The last line has no semicolon so MATLAB prints "c = 10".',
      },
      {
        id: 'M1_C5',
        module: 1,
        type: 'fix_bug',
        title: 'Colon Operator Range',
        description: 'This code should create a vector from 0 to 1 in steps of 0.2: [0, 0.2, 0.4, 0.6, 0.8, 1.0]. Fix the step size.',
        brokenCode: 'v = 0:0.5:1;\ndisp(v)',
        correctCode: 'v = 0:0.2:1;\ndisp(v)',
        expectedOutput: '  0  0.2000  0.4000  0.6000  0.8000  1.0000',
        hints: [
          'The colon operator syntax is start:step:end.',
          'The current step is 0.5. What should it be to get 6 evenly spaced values from 0 to 1?',
          'Change 0.5 to 0.2.',
        ],
        explanation: 'The colon operator start:step:end creates a vector. 0:0.2:1 gives [0, 0.2, 0.4, 0.6, 0.8, 1.0].',
        validator: (code) => /0\s*:\s*0\.2\s*:\s*1/.test(code),
      },
    ],
  },
  {
    id: 2,
    name: 'Using Functions',
    shortName: 'Functions',
    challenges: [
      {
        id: 'M2_C1',
        module: 2,
        type: 'fix_bug',
        title: 'Wrong Function Call',
        description: 'This code should compute the square root of 144, but it computes the square instead. Fix it.',
        brokenCode: 'x = 144;\nresult = x^2;\ndisp(result)',
        correctCode: 'x = 144;\nresult = sqrt(x);\ndisp(result)',
        expectedOutput: '    12',
        hints: [
          'The code squares x instead of taking its square root.',
          'MATLAB has a built-in function for square root.',
          'Replace x^2 with sqrt(x).',
        ],
        explanation: 'sqrt(x) returns the square root. x^2 raises x to the power of 2.',
        validator: (code) => /sqrt\s*\(\s*x\s*\)/.test(code),
      },
      {
        id: 'M2_C2',
        module: 2,
        type: 'fix_bug',
        title: 'Degrees vs Radians',
        description: 'This code should compute sin(90 degrees) = 1, but gets the wrong answer. Fix it.',
        brokenCode: "angle = 90;\nresult = sin(angle);\nfprintf('sin(90 deg) = %.4f\\n', result)",
        correctCode: "angle = 90;\nresult = sind(angle);\nfprintf('sin(90 deg) = %.4f\\n', result)",
        expectedOutput: 'sin(90 deg) = 1.0000',
        hints: [
          'MATLAB\'s sin() function expects radians, not degrees.',
          'MATLAB has a variant of sin that takes degrees directly.',
          'Use sind() instead of sin() for degree input.',
        ],
        explanation: 'sin() takes radians. sind() takes degrees. sin(pi/2)=1 and sind(90)=1.',
        validator: (code) => /sind\s*\(/.test(code) && !/[^i]sin\s*\(/.test(code.replace('sind', '')),
      },
      {
        id: 'M2_C3',
        module: 2,
        type: 'fix_bug',
        title: 'Rounding Down',
        description: 'This code should round 7.8 DOWN to 7, but gets 8 instead. Fix the function used.',
        brokenCode: 'x = 7.8;\nresult = round(x);\ndisp(result)',
        correctCode: 'x = 7.8;\nresult = floor(x);\ndisp(result)',
        expectedOutput: '     7',
        hints: [
          'round() rounds to the nearest integer. What function always rounds down?',
          'Think about floor and ceiling of a number.',
          'Use floor(x) to always round down.',
        ],
        explanation: 'round() rounds to nearest integer. floor() always rounds down. ceil() always rounds up.',
        validator: (code) => /floor\s*\(\s*x\s*\)/.test(code),
      },
      {
        id: 'M2_C4',
        module: 2,
        type: 'fix_bug',
        title: 'Size Function Outputs',
        description: 'This code should get the number of rows in a 2x3 matrix. Fix it so "rows" contains only the row count (2).',
        brokenCode: 'A = [1 2 3; 4 5 6];\nrows = size(A);\ndisp(rows)',
        correctCode: 'A = [1 2 3; 4 5 6];\nrows = size(A, 1);\ndisp(rows)',
        expectedOutput: '     2',
        hints: [
          'size(A) returns both rows and columns as a vector.',
          'size() accepts a second argument to specify which dimension.',
          'Use size(A, 1) to get only the row count.',
        ],
        explanation: 'size(A) returns [rows, cols]. size(A,1) returns just rows, size(A,2) returns just columns.',
        validator: (code) => /size\s*\(\s*A\s*,\s*1\s*\)/.test(code),
      },
      {
        id: 'M2_C5',
        module: 2,
        type: 'predict_output',
        title: 'Predict: rem and mod',
        description: 'What does this code display?\n\nx = rem(17, 5);\nfprintf(\'%d\\n\', x)',
        brokenCode: "x = rem(17, 5);\nfprintf('%d\\n', x)",
        correctCode: '2',
        expectedOutput: '2',
        hints: [
          'rem(a,b) returns the remainder after dividing a by b.',
          '17 / 5 = 3 remainder ?',
          '17 = 5*3 + 2, so rem(17,5) = 2.',
        ],
        explanation: 'rem(a,b) computes the remainder of a/b. 17/5 = 3 with remainder 2.',
      },
    ],
  },
  {
    id: 3,
    name: 'Matrices',
    shortName: 'Matrices',
    challenges: [
      {
        id: 'M3_C1',
        module: 3,
        type: 'fix_bug',
        title: 'Matrix Indexing Swap',
        description: 'This code should extract the element at row 2, column 3 of matrix A (which is 6). The indices are swapped. Fix it.',
        brokenCode: 'A = [1 2 3; 4 5 6];\nresult = A(3, 2);\ndisp(result)',
        correctCode: 'A = [1 2 3; 4 5 6];\nresult = A(2, 3);\ndisp(result)',
        expectedOutput: '     6',
        hints: [
          'MATLAB indexing is A(row, column).',
          'Row 2, column 3 means A(2,3), not A(3,2).',
          'Swap the indices: change A(3,2) to A(2,3).',
        ],
        explanation: 'MATLAB uses (row, col) indexing. A(2,3) gets row 2, column 3.',
        validator: (code) => /A\s*\(\s*2\s*,\s*3\s*\)/.test(code),
      },
      {
        id: 'M3_C2',
        module: 3,
        type: 'fix_bug',
        title: 'Extract a Column',
        description: 'This code should extract the entire second column of A, but it extracts the second row instead. Fix it.',
        brokenCode: 'A = [1 2; 3 4; 5 6];\ncol2 = A(2, :);\ndisp(col2)',
        correctCode: 'A = [1 2; 3 4; 5 6];\ncol2 = A(:, 2);\ndisp(col2)',
        expectedOutput: '     2\n     4\n     6',
        hints: [
          'The colon : means "all" when used as an index.',
          'A(2,:) gets all columns of row 2. A(:,2) gets all rows of column 2.',
          'Change A(2,:) to A(:,2).',
        ],
        explanation: 'A(:,j) selects all rows of column j. A(i,:) selects all columns of row i.',
        validator: (code) => /A\s*\(\s*:\s*,\s*2\s*\)/.test(code),
      },
      {
        id: 'M3_C3',
        module: 3,
        type: 'fix_bug',
        title: 'Horizontal Concatenation',
        description: 'This code should horizontally concatenate A and B to get [1 2 5 6; 3 4 7 8], but it stacks them vertically. Fix it.',
        brokenCode: 'A = [1 2; 3 4];\nB = [5 6; 7 8];\nC = [A; B];\ndisp(C)',
        correctCode: 'A = [1 2; 3 4];\nB = [5 6; 7 8];\nC = [A, B];\ndisp(C)',
        expectedOutput: '     1     2     5     6\n     3     4     7     8',
        hints: [
          'Semicolons in [] stack vertically, commas place side-by-side.',
          '[A; B] stacks A on top of B. [A, B] places B next to A.',
          'Change [A; B] to [A, B].',
        ],
        explanation: '[A, B] concatenates horizontally. [A; B] concatenates vertically.',
        validator: (code) => /\[\s*A\s*,\s*B\s*\]/.test(code),
      },
      {
        id: 'M3_C4',
        module: 3,
        type: 'fix_bug',
        title: 'Identity Matrix',
        description: 'This code should create a 3x3 identity matrix, but it creates a 3x3 matrix of ones instead. Fix it.',
        brokenCode: 'I = ones(3);\ndisp(I)',
        correctCode: 'I = eye(3);\ndisp(I)',
        expectedOutput: '     1     0     0\n     0     1     0\n     0     0     1',
        hints: [
          'An identity matrix has 1s on the diagonal and 0s elsewhere.',
          'ones() fills everything with 1. What function creates an identity matrix?',
          'Use eye(3) instead of ones(3).',
        ],
        explanation: 'eye(n) creates an identity matrix. ones(n) creates all 1s. zeros(n) creates all 0s.',
        validator: (code) => /eye\s*\(\s*3\s*\)/.test(code),
      },
      {
        id: 'M3_C5',
        module: 3,
        type: 'predict_output',
        title: 'Predict: Matrix Size',
        description: 'What does this code display?\n\nA = [1 2 3; 4 5 6];\nB = A\';\nfprintf(\'%d x %d\\n\', size(B))',
        brokenCode: "A = [1 2 3; 4 5 6];\nB = A';\nfprintf('%d x %d\\n', size(B))",
        correctCode: '3 x 2',
        expectedOutput: '3 x 2',
        hints: [
          'The transpose operator (\') flips rows and columns.',
          'A is 2x3. What is the size of A transposed?',
          'A\' is 3x2, so size(B) = [3, 2].',
        ],
        explanation: 'Transposing a 2x3 matrix gives a 3x2 matrix.',
      },
    ],
  },
  {
    id: 4,
    name: 'Plotting',
    shortName: 'Plotting',
    challenges: [
      {
        id: 'M4_C1',
        module: 4,
        type: 'fix_bug',
        title: 'Mismatched Vector Lengths',
        description: 'This code tries to plot y vs x but crashes because the vectors have different lengths. Fix it.',
        brokenCode: 'x = 1:5;\ny = [2 4 6 8];\nplot(x, y)',
        correctCode: 'x = 1:5;\ny = [2 4 6 8 10];\nplot(x, y)',
        expectedOutput: '(plot displayed)',
        hints: [
          'plot(x,y) requires x and y to have the same number of elements.',
          'x has 5 elements (1:5) but y has only 4.',
          'Add a 5th element to y, e.g., [2 4 6 8 10].',
        ],
        explanation: 'plot(x,y) requires x and y to be the same length. Always check vector dimensions before plotting.',
        validator: (code) => {
          const yMatch = code.match(/y\s*=\s*\[([^\]]+)\]/);
          if (!yMatch) return false;
          const elements = yMatch[1].split(/[\s,]+/).filter(Boolean);
          return elements.length === 5;
        },
      },
      {
        id: 'M4_C2',
        module: 4,
        type: 'fix_bug',
        title: 'Axis Labels Swapped',
        description: 'The x-axis should be labeled "Time (s)" and y-axis "Voltage (V)", but they are swapped. Fix it.',
        brokenCode: "x = 0:0.1:1;\ny = sin(2*pi*x);\nplot(x, y);\nxlabel('Voltage (V)');\nylabel('Time (s)');\ntitle('Signal')",
        correctCode: "x = 0:0.1:1;\ny = sin(2*pi*x);\nplot(x, y);\nxlabel('Time (s)');\nylabel('Voltage (V)');\ntitle('Signal')",
        expectedOutput: '(plot with correct labels)',
        hints: [
          'Look at which label goes with which axis function.',
          'xlabel() labels the horizontal axis, ylabel() labels the vertical axis.',
          'Swap the strings: xlabel(\'Time (s)\') and ylabel(\'Voltage (V)\').',
        ],
        explanation: 'xlabel() sets the horizontal axis label, ylabel() sets the vertical. Match them to what each axis represents.',
        validator: (code) => /xlabel\s*\(\s*'Time\s*\(s\)'\s*\)/.test(code) && /ylabel\s*\(\s*'Voltage\s*\(V\)'\s*\)/.test(code),
      },
      {
        id: 'M4_C3',
        module: 4,
        type: 'fix_bug',
        title: 'Subplot Overlap',
        description: 'This code should show two plots side by side (1 row, 2 columns), but both end up in the same subplot. Fix it.',
        brokenCode: "x = 0:0.1:2*pi;\nsubplot(1,2,1);\nplot(x, sin(x));\ntitle('Sine');\nsubplot(1,2,1);\nplot(x, cos(x));\ntitle('Cosine')",
        correctCode: "x = 0:0.1:2*pi;\nsubplot(1,2,1);\nplot(x, sin(x));\ntitle('Sine');\nsubplot(1,2,2);\nplot(x, cos(x));\ntitle('Cosine')",
        expectedOutput: '(two side-by-side plots)',
        hints: [
          'subplot(rows, cols, index) selects which subplot to draw in.',
          'Both plots use subplot(1,2,1) — the second one should use a different index.',
          'Change the second subplot call to subplot(1,2,2).',
        ],
        explanation: 'subplot(r,c,n) creates a grid and selects the nth plot. Each plot needs a unique index.',
        validator: (code) => {
          const matches = [...code.matchAll(/subplot\s*\(\s*1\s*,\s*2\s*,\s*(\d)\s*\)/g)];
          return matches.length >= 2 && matches[0][1] === '1' && matches[1][1] === '2';
        },
      },
      {
        id: 'M4_C4',
        module: 4,
        type: 'fix_bug',
        title: 'Element-wise Power',
        description: 'This code should compute y = x² element-wise for a vector, but crashes with a dimension error. Fix the operator.',
        brokenCode: 'x = 1:5;\ny = x^2;\ndisp(y)',
        correctCode: 'x = 1:5;\ny = x.^2;\ndisp(y)',
        expectedOutput: '     1     4     9    16    25',
        hints: [
          'x^2 tries matrix exponentiation, which requires a square matrix.',
          'For element-wise operations on vectors, MATLAB uses a dot prefix.',
          'Change x^2 to x.^2 for element-wise squaring.',
        ],
        explanation: 'The dot operator (.^, .*, ./) performs element-wise operations. Without the dot, MATLAB attempts matrix operations.',
        validator: (code) => /x\s*\.\^\s*2/.test(code),
      },
      {
        id: 'M4_C5',
        module: 4,
        type: 'predict_output',
        title: 'Predict: Number of Subplots',
        description: 'How many individual plot areas does this create?\n\nsubplot(2,3,1);\nsubplot(2,3,4);\nsubplot(2,3,6);',
        brokenCode: 'subplot(2,3,1);\nsubplot(2,3,4);\nsubplot(2,3,6);',
        correctCode: '3',
        expectedOutput: '3',
        hints: [
          'subplot(2,3,n) creates a 2x3 grid. Each call activates one subplot.',
          'Count the unique subplot indices used: 1, 4, 6.',
          'Three unique subplots are created.',
        ],
        explanation: 'subplot(2,3,n) defines a 2x3 grid of 6 possible plots. Only 3 are used (indices 1, 4, 6).',
      },
    ],
  },
  // --- MODULE 5: User Functions ---
  {
    id: 5,
    name: 'User Functions',
    shortName: 'Functions II',
    challenges: [
      {
        id: 'M5_C1',
        module: 5,
        type: 'fix_bug',
        title: 'Function Output Missing',
        description: 'This function should return the area of a circle, but it never assigns the output variable. Fix it.',
        brokenCode: 'function area = circleArea(r)\n    pi * r^2;\nend',
        correctCode: 'function area = circleArea(r)\n    area = pi * r^2;\nend',
        expectedOutput: 'area = 78.5398 (for r=5)',
        hints: [
          'The function declares "area" as the output variable.',
          'The computation runs but never assigns the result to "area".',
          'Add "area = " before pi * r^2.',
        ],
        explanation: 'In MATLAB functions, you must explicitly assign to the declared output variable name. Just computing a value doesn\'t return it.',
        validator: (code) => /area\s*=\s*pi\s*\*\s*r\s*\^\s*2/.test(code),
      },
      {
        id: 'M5_C2',
        module: 5,
        type: 'fix_bug',
        title: 'Wrong Number of Inputs',
        description: 'This function should accept length and width, but the definition only takes one input. Fix the function signature.',
        brokenCode: 'function a = rectArea(l)\n    a = l * w;\nend',
        correctCode: 'function a = rectArea(l, w)\n    a = l * w;\nend',
        expectedOutput: 'a = 20 (for l=4, w=5)',
        hints: [
          'The function body uses variable "w" but the signature doesn\'t include it.',
          'Multiple input arguments are separated by commas in the function line.',
          'Change rectArea(l) to rectArea(l, w).',
        ],
        explanation: 'All variables used in a function must either be input arguments, defined locally, or global. Missing inputs cause "undefined variable" errors.',
        validator: (code) => /function\s+a\s*=\s*rectArea\s*\(\s*l\s*,\s*w\s*\)/.test(code),
      },
      {
        id: 'M5_C3',
        module: 5,
        type: 'fix_bug',
        title: 'Multiple Outputs',
        description: 'This function should return both the area AND perimeter of a rectangle, but only declares one output. Fix it.',
        brokenCode: 'function area = rectProps(l, w)\n    area = l * w;\n    perim = 2*(l + w);\nend',
        correctCode: 'function [area, perim] = rectProps(l, w)\n    area = l * w;\n    perim = 2*(l + w);\nend',
        expectedOutput: '[area, perim] = rectProps(4, 5) -> 20, 18',
        hints: [
          'MATLAB functions can return multiple outputs using square brackets.',
          'The function computes perim but doesn\'t declare it as an output.',
          'Change "function area = ..." to "function [area, perim] = ...".',
        ],
        explanation: 'Multiple outputs are declared as [out1, out2] = funcName(in). The caller uses [a, p] = rectProps(4, 5) to capture both.',
        validator: (code) => /function\s*\[\s*area\s*,\s*perim\s*\]/.test(code),
      },
      {
        id: 'M5_C4',
        module: 5,
        type: 'fix_bug',
        title: 'Function vs Script Name',
        description: 'This function file computes BMI but the function name doesn\'t match. The file is saved as "calcBMI.m". Fix the function name.',
        brokenCode: 'function bmi = computeBMI(weight, height)\n    bmi = weight / height^2;\nend',
        correctCode: 'function bmi = calcBMI(weight, height)\n    bmi = weight / height^2;\nend',
        expectedOutput: 'bmi = 24.69 (for 75kg, 1.74m)',
        hints: [
          'In MATLAB, the function name should match the filename.',
          'The file is called calcBMI.m but the function is named computeBMI.',
          'Change computeBMI to calcBMI.',
        ],
        explanation: 'MATLAB requires the function name to match the .m filename. A mismatch causes warnings or errors when calling the function.',
        validator: (code) => /function\s+bmi\s*=\s*calcBMI\s*\(/.test(code),
      },
      {
        id: 'M5_C5',
        module: 5,
        type: 'predict_output',
        title: 'Predict: Variable Scope',
        description: 'What does this display?\n\nx = 10;\nresult = addFive(x);\nfprintf(\'%d\\n\', result)\n\nfunction y = addFive(n)\n    n = n + 5;\n    y = n;\nend',
        brokenCode: "x = 10;\nresult = addFive(x);\nfprintf('%d\\n', result)\n\nfunction y = addFive(n)\n    n = n + 5;\n    y = n;\nend",
        correctCode: '15',
        expectedOutput: '15',
        hints: [
          'The function receives x as n, adds 5 to n, and returns it as y.',
          'n = 10 + 5 = 15, y = 15, result = 15.',
          'Modifying n inside the function does NOT change x outside.',
        ],
        explanation: 'MATLAB functions have their own workspace. Changing n inside addFive doesn\'t affect x in the caller. result gets the returned value 15.',
      },
    ],
  },
  // --- MODULE 6: User I/O ---
  {
    id: 6,
    name: 'User I/O',
    shortName: 'I/O',
    challenges: [
      {
        id: 'M6_C1',
        module: 6,
        type: 'fix_bug',
        title: 'fprintf Format Specifier',
        description: 'This code should print "Temperature: 98.6 F" but prints "Temperature: 98 F" (no decimal). Fix the format specifier.',
        brokenCode: "temp = 98.6;\nfprintf('Temperature: %d F\\n', temp)",
        correctCode: "temp = 98.6;\nfprintf('Temperature: %.1f F\\n', temp)",
        expectedOutput: 'Temperature: 98.6 F',
        hints: [
          '%d is for integers. What format specifier shows decimal places?',
          'Use %f for floating-point numbers. %.1f shows 1 decimal place.',
          'Change %d to %.1f.',
        ],
        explanation: '%d truncates to integer. %f prints floating-point. %.1f shows 1 decimal, %.2f shows 2 decimals, etc.',
        validator: (code) => /%\.?\d*f/.test(code) && !/(?<!\\)%d/.test(code.split('fprintf')[1] || ''),
      },
      {
        id: 'M6_C2',
        module: 6,
        type: 'fix_bug',
        title: 'disp vs fprintf',
        description: 'This code should print "Hello, Alice" but instead prints the format string literally. Fix it.',
        brokenCode: "name = 'Alice';\ndisp('Hello, %s', name)",
        correctCode: "name = 'Alice';\nfprintf('Hello, %s\\n', name)",
        expectedOutput: 'Hello, Alice',
        hints: [
          'disp() doesn\'t support format specifiers like %s.',
          'Which function handles formatted output with placeholders?',
          'Use fprintf() instead of disp() for formatted strings.',
        ],
        explanation: 'disp() prints values as-is. fprintf() supports format specifiers (%s, %d, %f, etc.) for formatted output.',
        validator: (code) => /fprintf\s*\(/.test(code) && /%s/.test(code),
      },
      {
        id: 'M6_C3',
        module: 6,
        type: 'fix_bug',
        title: 'Input Prompt String',
        description: 'This code should ask the user for their age as a number, but the input() call treats it as a string. Fix it.',
        brokenCode: "age = input('Enter your age: ', 's');\nfprintf('You are %d years old\\n', age)",
        correctCode: "age = input('Enter your age: ');\nfprintf('You are %d years old\\n', age)",
        expectedOutput: 'You are 21 years old',
        hints: [
          'The \'s\' flag in input() makes it return a string instead of a number.',
          'For numerical input, input() should be called without the \'s\' flag.',
          'Remove the \'s\' argument from input().',
        ],
        explanation: 'input(prompt) returns a number. input(prompt, \'s\') returns a string. Use the right form for your data type.',
        validator: (code) => /input\s*\(\s*'[^']*'\s*\)/.test(code) && !/input\s*\([^)]*'s'/.test(code),
      },
      {
        id: 'M6_C4',
        module: 6,
        type: 'fix_bug',
        title: 'File Write Mode',
        description: 'This code should append to a log file, but it overwrites it each time. Fix the fopen mode.',
        brokenCode: "fid = fopen('log.txt', 'w');\nfprintf(fid, 'New entry\\n');\nfclose(fid);",
        correctCode: "fid = fopen('log.txt', 'a');\nfprintf(fid, 'New entry\\n');\nfclose(fid);",
        expectedOutput: '(appends to file instead of overwriting)',
        hints: [
          'fopen modes: \'w\' writes (overwrites), \'r\' reads. What mode appends?',
          'The \'a\' mode opens a file for appending.',
          'Change \'w\' to \'a\' in the fopen call.',
        ],
        explanation: 'fopen modes: \'r\' = read, \'w\' = write (overwrite), \'a\' = append. Use \'a\' to add to existing files without erasing them.',
        validator: (code) => /fopen\s*\([^)]*'a'\s*\)/.test(code),
      },
      {
        id: 'M6_C5',
        module: 6,
        type: 'predict_output',
        title: 'Predict: fprintf Formatting',
        description: 'What does this code print?\n\nx = 3.14159;\nfprintf(\'Value: %8.2f\\n\', x)',
        brokenCode: "x = 3.14159;\nfprintf('Value: %8.2f\\n', x)",
        correctCode: 'Value:     3.14',
        expectedOutput: 'Value:     3.14',
        hints: [
          '%8.2f means: 8 characters total width, 2 decimal places.',
          '3.14 is 4 characters. With 8 total width, there are leading spaces.',
          'The output is "Value:     3.14" (4 spaces + 3.14 = 8 chars).',
        ],
        explanation: '%8.2f formats a float in a field 8 characters wide with 2 decimal places. Shorter numbers get left-padded with spaces.',
      },
    ],
  },
  // --- MODULE 7: Statistics ---
  {
    id: 7,
    name: 'Statistics',
    shortName: 'Stats',
    challenges: [
      {
        id: 'M7_C1',
        module: 7,
        type: 'fix_bug',
        title: 'Mean vs Median',
        description: 'This code should compute the median of the data, but computes the mean instead. Fix it.',
        brokenCode: 'data = [1 2 3 4 100];\nresult = mean(data);\nfprintf(\'Central value: %g\\n\', result)',
        correctCode: 'data = [1 2 3 4 100];\nresult = median(data);\nfprintf(\'Central value: %g\\n\', result)',
        expectedOutput: 'Central value: 3',
        hints: [
          'mean() computes the average, which is skewed by outliers like 100.',
          'What function gives the middle value of sorted data?',
          'Use median() instead of mean().',
        ],
        explanation: 'mean() averages all values (sensitive to outliers). median() returns the middle value when sorted, which is more robust to outliers.',
        validator: (code) => /median\s*\(\s*data\s*\)/.test(code),
      },
      {
        id: 'M7_C2',
        module: 7,
        type: 'fix_bug',
        title: 'Standard Deviation Flag',
        description: 'This code should compute the sample standard deviation (N-1), but computes the population std (N). Fix the flag.',
        brokenCode: 'data = [4 7 13 2 1];\ns = std(data, 1);\nfprintf(\'Std dev: %.2f\\n\', s)',
        correctCode: 'data = [4 7 13 2 1];\ns = std(data, 0);\nfprintf(\'Std dev: %.2f\\n\', s)',
        expectedOutput: 'Std dev: 4.72',
        hints: [
          'std(data, 1) uses N (population). std(data, 0) uses N-1 (sample).',
          'For sample statistics (typical in engineering), use the N-1 normalization.',
          'Change std(data, 1) to std(data, 0) or just std(data).',
        ],
        explanation: 'std(x,0) or std(x) uses N-1 (sample std, default). std(x,1) uses N (population std). Sample std is more common in engineering.',
        validator: (code) => /std\s*\(\s*data\s*,\s*0\s*\)/.test(code) || /std\s*\(\s*data\s*\)\s*;?/.test(code),
      },
      {
        id: 'M7_C3',
        module: 7,
        type: 'fix_bug',
        title: 'Histogram Bin Count',
        description: 'This code should create a histogram with 10 bins, but the bins argument is in the wrong position. Fix it.',
        brokenCode: 'data = randn(1, 1000);\nhistogram(10, data)',
        correctCode: 'data = randn(1, 1000);\nhistogram(data, 10)',
        expectedOutput: '(histogram with 10 bins)',
        hints: [
          'Check the argument order for histogram().',
          'histogram(data, nbins) — data comes first, then bin count.',
          'Swap the arguments: histogram(data, 10).',
        ],
        explanation: 'histogram(data, nbins) takes data first, then optional bin count. Getting the order wrong causes errors or unexpected plots.',
        validator: (code) => /histogram\s*\(\s*data\s*,\s*10\s*\)/.test(code),
      },
      {
        id: 'M7_C4',
        module: 7,
        type: 'fix_bug',
        title: 'Random Seed for Reproducibility',
        description: 'This code should generate the SAME random numbers every time it runs. Add the missing seed command before rng.',
        brokenCode: 'x = rand(1, 5);\ndisp(x)',
        correctCode: 'rng(42);\nx = rand(1, 5);\ndisp(x)',
        expectedOutput: '(same 5 random numbers every run)',
        hints: [
          'rand() gives different numbers each time unless you set a seed.',
          'MATLAB uses rng() to set the random number generator seed.',
          'Add rng(42); (or any number) before the rand() call.',
        ],
        explanation: 'rng(seed) sets the random number generator to a known state. This makes rand(), randn(), etc. produce reproducible results.',
        validator: (code) => /rng\s*\(\s*\d+\s*\)/.test(code) && /rand\s*\(/.test(code),
      },
      {
        id: 'M7_C5',
        module: 7,
        type: 'predict_output',
        title: 'Predict: Normal Distribution',
        description: 'What does this code compute?\n\ndata = [2 4 4 4 5 5 7 9];\nm = mean(data);\nfprintf(\'%.0f\\n\', m)',
        brokenCode: "data = [2 4 4 4 5 5 7 9];\nm = mean(data);\nfprintf('%.0f\\n', m)",
        correctCode: '5',
        expectedOutput: '5',
        hints: [
          'mean() sums all values and divides by count.',
          '2+4+4+4+5+5+7+9 = 40. There are 8 values.',
          '40/8 = 5.0, and %.0f shows 0 decimal places.',
        ],
        explanation: 'mean([2 4 4 4 5 5 7 9]) = 40/8 = 5. The format %.0f rounds to 0 decimal places.',
      },
    ],
  },
  // --- MODULE 8: Logical Functions ---
  {
    id: 8,
    name: 'Logical Functions',
    shortName: 'Logic',
    challenges: [
      {
        id: 'M8_C1',
        module: 8,
        type: 'fix_bug',
        title: 'Assignment vs Comparison',
        description: 'This if-statement should CHECK if x equals 5, but it ASSIGNS 5 to x instead. Fix it.',
        brokenCode: "x = 3;\nif x = 5\n    disp('equal')\nend",
        correctCode: "x = 3;\nif x == 5\n    disp('equal')\nend",
        expectedOutput: '(nothing printed, since 3 ~= 5)',
        hints: [
          '= is assignment, == is comparison in MATLAB.',
          'if x = 5 assigns 5 to x. if x == 5 checks equality.',
          'Change = to == in the if condition.',
        ],
        explanation: '= assigns a value. == tests equality. This is one of the most common bugs in programming. MATLAB will error on "if x = 5".',
        validator: (code) => /if\s+x\s*==\s*5/.test(code),
      },
      {
        id: 'M8_C2',
        module: 8,
        type: 'fix_bug',
        title: 'elseif Spelling',
        description: 'This code has a syntax error in the conditional. Fix the misspelled keyword.',
        brokenCode: "score = 85;\nif score >= 90\n    grade = 'A';\nelse if score >= 80\n    grade = 'B';\nend\ndisp(grade)",
        correctCode: "score = 85;\nif score >= 90\n    grade = 'A';\nelseif score >= 80\n    grade = 'B';\nend\ndisp(grade)",
        expectedOutput: 'B',
        hints: [
          'Look at how the second condition is written.',
          '"else if" (two words) is not the same as "elseif" (one word) in MATLAB.',
          'Change "else if" to "elseif" (no space).',
        ],
        explanation: 'MATLAB uses "elseif" (one word). Writing "else if" creates a nested if inside the else, which requires its own extra "end".',
        validator: (code) => /elseif/.test(code) && !/else\s+if/.test(code),
      },
      {
        id: 'M8_C3',
        module: 8,
        type: 'fix_bug',
        title: 'Logical OR Operator',
        description: 'This code should check if x is less than 0 OR greater than 100, but uses the wrong operator. Fix it.',
        brokenCode: "x = 150;\nif x < 0 & x > 100\n    disp('Out of range')\nend",
        correctCode: "x = 150;\nif x < 0 || x > 100\n    disp('Out of range')\nend",
        expectedOutput: 'Out of range',
        hints: [
          '& means AND — both conditions must be true. x can\'t be < 0 AND > 100 simultaneously.',
          'You need OR: at least one condition must be true.',
          'Change & to || (logical OR).',
        ],
        explanation: '& (and) requires both true. | or || (or) requires at least one true. || short-circuits (stops at first true), which is preferred for scalars.',
        validator: (code) => /x\s*<\s*0\s*\|\|?\s*x\s*>\s*100/.test(code),
      },
      {
        id: 'M8_C4',
        module: 8,
        type: 'fix_bug',
        title: 'Switch Case Missing Break',
        description: 'This switch statement should print only the matching case, but MATLAB switch doesn\'t need break. The real bug: the case value is wrong. Fix it.',
        brokenCode: "day = 'Mon';\nswitch day\n    case 'Monday'\n        disp('Start of week')\n    case 'Friday'\n        disp('End of week')\n    otherwise\n        disp('Midweek')\nend",
        correctCode: "day = 'Mon';\nswitch day\n    case 'Mon'\n        disp('Start of week')\n    case 'Friday'\n        disp('End of week')\n    otherwise\n        disp('Midweek')\nend",
        expectedOutput: 'Start of week',
        hints: [
          'The variable day is \'Mon\' but the case checks for \'Monday\'.',
          'switch compares the exact value — \'Mon\' does not equal \'Monday\'.',
          'Change case \'Monday\' to case \'Mon\' to match the variable.',
        ],
        explanation: 'switch/case does exact string comparison. \'Mon\' ~= \'Monday\'. Unlike C/Java, MATLAB switch does NOT fall through and doesn\'t need break.',
        validator: (code) => /case\s+'Mon'/.test(code) && !/case\s+'Monday'/.test(code),
      },
      {
        id: 'M8_C5',
        module: 8,
        type: 'predict_output',
        title: 'Predict: Nested If',
        description: 'What does this code display?\n\nx = 7;\nif x > 10\n    disp(\'A\')\nelseif x > 5\n    disp(\'B\')\nelseif x > 0\n    disp(\'C\')\nend',
        brokenCode: "x = 7;\nif x > 10\n    disp('A')\nelseif x > 5\n    disp('B')\nelseif x > 0\n    disp('C')\nend",
        correctCode: 'B',
        expectedOutput: 'B',
        hints: [
          'x=7. Check conditions top to bottom: 7>10? No. 7>5? ...',
          '7 > 5 is true, so it enters that branch and skips the rest.',
          'Output is B. Even though 7>0 is also true, elseif stops at the first match.',
        ],
        explanation: 'elseif chains are evaluated top-down. The first true condition executes; the rest are skipped. 7>5 is true so B is printed.',
      },
    ],
  },
  // --- MODULE 9: Loops ---
  {
    id: 9,
    name: 'Loops',
    shortName: 'Loops',
    challenges: [
      {
        id: 'M9_C1',
        module: 9,
        type: 'fix_bug',
        title: 'For Loop Range',
        description: 'This loop should print numbers 1 through 5, but it only prints 1. Fix the loop range.',
        brokenCode: 'for i = 1\n    fprintf(\'%d \', i)\nend',
        correctCode: 'for i = 1:5\n    fprintf(\'%d \', i)\nend',
        expectedOutput: '1 2 3 4 5',
        hints: [
          '"for i = 1" only runs once with i=1. How do you specify a range?',
          'Use the colon operator to create a range: 1:5.',
          'Change "for i = 1" to "for i = 1:5".',
        ],
        explanation: '"for i = 1" iterates over a single value. "for i = 1:5" iterates from 1 to 5. The colon creates the range vector.',
        validator: (code) => /for\s+i\s*=\s*1\s*:\s*5/.test(code),
      },
      {
        id: 'M9_C2',
        module: 9,
        type: 'fix_bug',
        title: 'While Loop Infinite',
        description: 'This while loop should count from 1 to 5, but it runs forever because the counter never updates. Fix it.',
        brokenCode: "n = 1;\nwhile n <= 5\n    fprintf('%d ', n)\nend",
        correctCode: "n = 1;\nwhile n <= 5\n    fprintf('%d ', n)\n    n = n + 1;\nend",
        expectedOutput: '1 2 3 4 5',
        hints: [
          'n starts at 1 and the loop checks n <= 5, but n never changes.',
          'You need to increment n inside the loop body.',
          'Add "n = n + 1;" before end.',
        ],
        explanation: 'While loops need their condition variable updated inside the loop body. Without incrementing n, n<=5 is always true = infinite loop.',
        validator: (code) => /n\s*=\s*n\s*\+\s*1/.test(code) || /n\s*=\s*n\s*\+\s*1/.test(code),
      },
      {
        id: 'M9_C3',
        module: 9,
        type: 'fix_bug',
        title: 'Accumulator Not Initialized',
        description: 'This code should sum numbers 1 to 10, but total is never initialized. Fix it.',
        brokenCode: 'for i = 1:10\n    total = total + i;\nend\ndisp(total)',
        correctCode: 'total = 0;\nfor i = 1:10\n    total = total + i;\nend\ndisp(total)',
        expectedOutput: '    55',
        hints: [
          'total is used before it\'s defined. MATLAB will error on "total + i" if total doesn\'t exist.',
          'Initialize accumulator variables before the loop.',
          'Add "total = 0;" before the for loop.',
        ],
        explanation: 'Accumulator variables must be initialized before use. total = 0 before the loop lets total = total + i work on each iteration.',
        validator: (code) => /total\s*=\s*0\s*;/.test(code) && code.indexOf('total = 0') < code.indexOf('for'),
      },
      {
        id: 'M9_C4',
        module: 9,
        type: 'fix_bug',
        title: 'Nested Loop Index Collision',
        description: 'This code should print a 3x3 grid of coordinates, but both loops use the same variable "i". Fix the inner loop.',
        brokenCode: "for i = 1:3\n    for i = 1:3\n        fprintf('(%d,%d) ', i, i)\n    end\n    fprintf('\\n')\nend",
        correctCode: "for i = 1:3\n    for j = 1:3\n        fprintf('(%d,%d) ', i, j)\n    end\n    fprintf('\\n')\nend",
        expectedOutput: '(1,1) (1,2) (1,3)\n(2,1) (2,2) (2,3)\n(3,1) (3,2) (3,3)',
        hints: [
          'Both loops use variable "i". The inner loop overwrites the outer loop\'s i.',
          'Use different variable names for nested loops.',
          'Change the inner loop variable from "i" to "j".',
        ],
        explanation: 'Nested loops must use different iteration variables. Using the same variable causes the inner loop to overwrite the outer one.',
        validator: (code) => /for\s+i\s*=/.test(code) && /for\s+j\s*=/.test(code),
      },
      {
        id: 'M9_C5',
        module: 9,
        type: 'predict_output',
        title: 'Predict: Break Statement',
        description: 'What does this code display?\n\nfor i = 1:10\n    if i == 4\n        break\n    end\n    fprintf(\'%d \', i)\nend',
        brokenCode: "for i = 1:10\n    if i == 4\n        break\n    end\n    fprintf('%d ', i)\nend",
        correctCode: '1 2 3',
        expectedOutput: '1 2 3',
        hints: [
          'The loop runs i=1,2,3,... and checks if i==4.',
          'When i reaches 4, break exits the loop BEFORE the fprintf.',
          'So it prints 1, 2, 3 then breaks. It does NOT print 4.',
        ],
        explanation: 'break immediately exits the loop. Since the break is before fprintf, i=4 is never printed. Output: 1 2 3.',
      },
    ],
  },
  // --- MODULE 10: Advanced Matrices ---
  {
    id: 10,
    name: 'Advanced Matrices',
    shortName: 'Adv. Matrix',
    challenges: [
      {
        id: 'M10_C1',
        module: 10,
        type: 'fix_bug',
        title: 'Matrix Multiplication vs Element-wise',
        description: 'This code should do element-wise multiplication of A and B, but does matrix multiplication instead. Fix it.',
        brokenCode: 'A = [1 2; 3 4];\nB = [5 6; 7 8];\nC = A * B;\ndisp(C)',
        correctCode: 'A = [1 2; 3 4];\nB = [5 6; 7 8];\nC = A .* B;\ndisp(C)',
        expectedOutput: '     5    12\n    21    32',
        hints: [
          '* does matrix multiplication. What operator does element-wise?',
          'The dot prefix (.*, ./, .^) means element-wise in MATLAB.',
          'Change A * B to A .* B.',
        ],
        explanation: 'A*B is matrix multiplication (dot products). A.*B multiplies corresponding elements: C(i,j) = A(i,j)*B(i,j).',
        validator: (code) => /A\s*\.\*\s*B/.test(code),
      },
      {
        id: 'M10_C2',
        module: 10,
        type: 'fix_bug',
        title: 'Solving Linear System',
        description: 'This code should solve Ax = b using the backslash operator, but uses the wrong operator direction. Fix it.',
        brokenCode: 'A = [2 1; 1 3];\nb = [5; 10];\nx = b / A;\ndisp(x)',
        correctCode: 'A = [2 1; 1 3];\nb = [5; 10];\nx = A \\ b;\ndisp(x)',
        expectedOutput: '    1\n    3',
        hints: [
          'b/A is "right division" (b * inv(A)). That solves xA = b.',
          'For Ax = b, you need "left division": A\\b.',
          'Change b / A to A \\ b.',
        ],
        explanation: 'A\\b solves Ax=b (left division). b/A solves xA=b (right division). For typical linear systems, use backslash: x = A\\b.',
        validator: (code) => /A\s*\\\s*b/.test(code),
      },
      {
        id: 'M10_C3',
        module: 10,
        type: 'fix_bug',
        title: 'Determinant Function',
        description: 'This code should compute the determinant of A, but uses the wrong function. Fix it.',
        brokenCode: 'A = [1 2; 3 4];\nd = inv(A);\nfprintf(\'Determinant: %g\\n\', d)',
        correctCode: 'A = [1 2; 3 4];\nd = det(A);\nfprintf(\'Determinant: %g\\n\', d)',
        expectedOutput: 'Determinant: -2',
        hints: [
          'inv(A) computes the inverse matrix, not the determinant.',
          'What function computes the determinant of a matrix?',
          'Use det(A) instead of inv(A).',
        ],
        explanation: 'det(A) returns the determinant (a scalar). inv(A) returns the inverse matrix. For a 2x2: det([a b; c d]) = ad - bc.',
        validator: (code) => /det\s*\(\s*A\s*\)/.test(code),
      },
      {
        id: 'M10_C4',
        module: 10,
        type: 'fix_bug',
        title: 'Matrix Dimension Mismatch',
        description: 'This code tries to multiply a 2x3 matrix by a 2x2 matrix, which is invalid. Fix matrix B so multiplication works.',
        brokenCode: 'A = [1 2 3; 4 5 6];\nB = [1 0; 0 1];\nC = A * B;\ndisp(C)',
        correctCode: 'A = [1 2 3; 4 5 6];\nB = [1 0; 0 1; 1 0];\nC = A * B;\ndisp(C)',
        expectedOutput: '     4     2\n    10     5',
        hints: [
          'For A*B, the number of columns in A must equal the number of rows in B.',
          'A is 2x3, so B must have 3 rows. Currently B is 2x2.',
          'Make B a 3x2 matrix, e.g., [1 0; 0 1; 1 0].',
        ],
        explanation: 'Matrix multiplication A(m×n) * B(n×p) = C(m×p). The inner dimensions must match. 2x3 requires B to be 3×something.',
        validator: (code) => {
          const bMatch = code.match(/B\s*=\s*\[([^\]]+)\]/);
          if (!bMatch) return false;
          const rows = bMatch[1].split(';').length;
          return rows === 3;
        },
      },
      {
        id: 'M10_C5',
        module: 10,
        type: 'predict_output',
        title: 'Predict: Matrix Inverse',
        description: 'What does this code display?\n\nA = [1 0; 0 1];\nB = inv(A);\nfprintf(\'%d %d\\n\', B(1,:))',
        brokenCode: "A = [1 0; 0 1];\nB = inv(A);\nfprintf('%d %d\\n', B(1,:))",
        correctCode: '1 0',
        expectedOutput: '1 0',
        hints: [
          'What is the inverse of the identity matrix?',
          'The identity matrix is its own inverse: inv(eye(n)) = eye(n).',
          'B = [1 0; 0 1], so B(1,:) = [1, 0]. Output: "1 0".',
        ],
        explanation: 'The inverse of the identity matrix is itself. inv([1 0; 0 1]) = [1 0; 0 1]. B(1,:) extracts the first row.',
      },
    ],
  },
  // --- MODULE 11: Numerical Methods ---
  {
    id: 11,
    name: 'Numerical Methods',
    shortName: 'Numerical',
    challenges: [
      {
        id: 'M11_C1',
        module: 11,
        type: 'fix_bug',
        title: 'Symbolic Variable Declaration',
        description: 'This code should create a symbolic expression, but forgot to declare x as symbolic. Fix it.',
        brokenCode: 'f = x^2 + 3*x + 2;\ndisp(f)',
        correctCode: 'syms x\nf = x^2 + 3*x + 2;\ndisp(f)',
        expectedOutput: 'x^2 + 3*x + 2',
        hints: [
          'x is used as a symbolic variable but was never declared.',
          'MATLAB needs "syms x" to create symbolic variables.',
          'Add "syms x" before the expression.',
        ],
        explanation: 'syms x declares x as a symbolic variable. Without it, MATLAB treats x as an undefined workspace variable and errors.',
        validator: (code) => /syms\s+x/.test(code) && /x\s*\^\s*2/.test(code),
      },
      {
        id: 'M11_C2',
        module: 11,
        type: 'fix_bug',
        title: 'Numerical Integration Function',
        description: 'This code should numerically integrate sin(x) from 0 to pi (answer: 2). Fix the function call.',
        brokenCode: 'f = @(x) sin(x);\nresult = diff(f, 0, pi);\nfprintf(\'Integral: %.4f\\n\', result)',
        correctCode: 'f = @(x) sin(x);\nresult = integral(f, 0, pi);\nfprintf(\'Integral: %.4f\\n\', result)',
        expectedOutput: 'Integral: 2.0000',
        hints: [
          'diff() computes differences/derivatives, not integrals.',
          'MATLAB uses integral() for numerical integration.',
          'Change diff(f, 0, pi) to integral(f, 0, pi).',
        ],
        explanation: 'integral(f, a, b) computes the numerical integral of f from a to b. diff() is for derivatives or differences.',
        validator: (code) => /integral\s*\(\s*f\s*,\s*0\s*,\s*pi\s*\)/.test(code),
      },
      {
        id: 'M11_C3',
        module: 11,
        type: 'fix_bug',
        title: 'Anonymous Function Syntax',
        description: 'This anonymous function should compute f(x) = x² - 4, but has a syntax error. Fix it.',
        brokenCode: 'f = (x) x^2 - 4;\nresult = f(3);\ndisp(result)',
        correctCode: 'f = @(x) x^2 - 4;\nresult = f(3);\ndisp(result)',
        expectedOutput: '     5',
        hints: [
          'Anonymous functions in MATLAB need the @ symbol.',
          'The syntax is: handle = @(inputs) expression.',
          'Add @ before (x): f = @(x) x^2 - 4.',
        ],
        explanation: 'Anonymous functions use @(args) expression syntax. The @ creates a function handle. f = @(x) x^2-4 then f(3) returns 5.',
        validator: (code) => /f\s*=\s*@\s*\(\s*x\s*\)/.test(code),
      },
      {
        id: 'M11_C4',
        module: 11,
        type: 'fix_bug',
        title: 'Root Finding',
        description: 'This code should find where x² - 4 = 0 (roots at x=2 and x=-2), but uses the wrong solver. Fix it.',
        brokenCode: 'f = @(x) x^2 - 4;\nroot = fminbnd(f, 0, 5);\nfprintf(\'Root: %.4f\\n\', root)',
        correctCode: 'f = @(x) x^2 - 4;\nroot = fzero(f, 3);\nfprintf(\'Root: %.4f\\n\', root)',
        expectedOutput: 'Root: 2.0000',
        hints: [
          'fminbnd finds the minimum of a function, not its zeros.',
          'What MATLAB function finds where f(x) = 0?',
          'Use fzero(f, initial_guess) to find roots.',
        ],
        explanation: 'fzero(f, x0) finds where f(x)=0 near x0. fminbnd(f, a, b) finds the minimum of f on [a,b]. Different goals entirely.',
        validator: (code) => /fzero\s*\(\s*f/.test(code),
      },
      {
        id: 'M11_C5',
        module: 11,
        type: 'predict_output',
        title: 'Predict: Symbolic Differentiation',
        description: 'What does this code display?\n\nsyms x\nf = x^3 + 2*x;\ndf = diff(f);\ndisp(df)',
        brokenCode: 'syms x\nf = x^3 + 2*x;\ndf = diff(f);\ndisp(df)',
        correctCode: '3*x^2 + 2',
        expectedOutput: '3*x^2 + 2',
        hints: [
          'diff() on a symbolic expression computes the derivative.',
          'd/dx of x³ = 3x², d/dx of 2x = 2.',
          'diff(x^3 + 2*x) = 3*x^2 + 2.',
        ],
        explanation: 'diff(f) symbolically differentiates f with respect to x. Power rule: d/dx(xⁿ) = n*x^(n-1). So x³ + 2x becomes 3x² + 2.',
      },
    ],
  },
];
